// src/components/admin/party/partyConstants.js
//
// All static data constants shared across party/ sub-components.
// No React or API imports — purely data.

// Fields that should be auto-uppercased on input
export const UPPERCASE_FIELDS = new Set([
  "gst", "pan", "cin", "tan", "ifscCode", "cSwiftCode", "cBankCode","cGstLutNo",
]);

// All customer fields that are compulsory
export const CUSTOMER_REQUIRED = [
  "companyName", "contactNumber", "email",
  "gst", "pan", "cin", "tan",
  "buyerAddress1", "buyerAddress2", "buyerAddress3",
  "shippingAddress1", "shippingAddress2", "shippingAddress3",
  "bankAccHolder", "bankName", "accountNumber", "micrCode", "ifscCode",
];

// Additional fields required for International customers
export const INTL_REQUIRED = ["cSwiftCode", "cBankCode", "cIban"];

// All party (contact) fields that are compulsory
export const PARTY_REQUIRED = ["name", "phone", "email"];

// DB CUST_TYPE actual stored values
export const CUSTOMER_TYPES = ["Local", "International"];

// UI labels for STATUS — maps to DB Integer 1/0 via party.js (customers)
// or DB String "Active"/"Inactive" directly (contacts)
export const STATUS_OPTIONS = ["Active", "Inactive"];

// Empty form defaults — ID excluded (auto-generated by DB)
export const EMPTY_CUSTOMER = {
  companyName: "", contactNumber: "", email: "", website: "",
  // DB CUST_TYPE column stores exactly "Local" or "International"
  customerType: "Local",
  gst: "", cin: "", pan: "", tan: "", cGstLutNo: "",
  // DB STATUS column stores Integer 1/0 — UI uses "Active"/"Inactive", converted in party.js
  status: "Active",
  buyerAddress1: "", buyerAddress2: "", buyerAddress3: "",
  shippingAddress1: "", shippingAddress2: "", shippingAddress3: "",
  bankAccHolder: "", bankName: "", accountNumber: "", micrCode: "",
  ifscCode: "", cSwiftCode: "", cBankCode: "", cIban: "",
  cBankBranchAdd1: "", cBankBranchAdd2: "", cBankBranchAdd3: "",
};

// DB PARTY_DIRECTORY.STATUS stores String "Active"/"Inactive"
export const EMPTY_CONTACT = { name: "", phone: "", email: "", status: "Active" };
